### ISSUE TITLE
Package test fail

### ISSUE THREAD

**Issue by nmailhot** [alecthomas/assert#2]
+ go test github.com/alecthomas/assert/
# github.com/alecthomas/assert
../../BUILDROOT/golang-github-alecthomas-assert-0-0.1.20170911git561411b.el7.centos.x86_64/usr/share/gocode/src/github.com/alecthomas/assert/assertions.go:311: not enough arguments in call to repr.OmitEmpty
../../BUILDROOT/golang-github-alecthomas-assert-0-0.1.20170911git561411b.el7.centos.x86_64/usr/share/gocode/src/github.com/alecthomas/assert/assertions.go:458: not enough arguments in call to repr.OmitEmpty
../../BUILDROOT/golang-github-alecthomas-assert-0-0.1.20170911git561411b.el7.centos.x86_64/usr/share/gocode/src/github.com/alecthomas/assert/diff.go:15: not enough arguments in call to repr.OmitEmpty
../../BUILDROOT/golang-github-alecthomas-assert-0-0.1.20170911git561411b.el7.centos.x86_64/usr/share/gocode/src/github.com/alecthomas/assert/diff.go:16: not enough arguments in call to repr.OmitEmpty

Installed:
  golang.x86_64 0:1.7.4-1.el7
  golang-github-alecthomas-colour-devel.x86_64 0:0-0.3.20170912git60882d9.el7.centos
  golang-github-alecthomas-repr-devel.x86_64 0:0-0.1.20170912gitcf65cb4.el7.centos
  golang-github-sergi-go-diff-devel.x86_64 0:0-0.2.20170911gitfeef008.el7.centos

Dependency Installed:
  golang-bin.x86_64 0:1.7.4-1.el7       golang-github-mattn-go-isatty-devel.x86_64 0:0.0.2-1.el7.centos       golang-src.noarch 0:1.7.4-1.el7

**Comment by alecthomas** [comment]
This should be fixed now!
